/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class aac_ndkopencv_OpencvNativeClass */

using namespace cv;
using namespace std;

#ifndef _Included_aac_scanner_ScannerNative
#define _Included_aac_scanner_ScannerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aac_scanner_ScannerNative
 * Method:    drawContours
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aac_scanner_ScannerNative_drawContours
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
